apiVersion: v1
kind: Service
metadata:
  name: sabza-backend-service
  namespace: sabza-namespace
spec:
  selector:
    app: sabza-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
