apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabza-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ziconcloudnew/Sabza-Franchise-master-Landing-Page.git
    targetRevision: main
    path: k8s/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: sabza-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
